# drop schema company if exists;
# create schema company if not exists;

drop schema land;
create schema land;
use land;


CREATE TABLE ATTRACT 
    ( 
     FACILITY_NO          INTEGER  NOT NULL, 
     ATTRACT_PERSON_LIMIT INTEGER , 
     ATTRACT_AGE_LIMIT    INTEGER , 
     ATTRACT_AGE_LIMIT1   INTEGER 
    ) 
;

ALTER TABLE ATTRACT 
    ADD CONSTRAINT PK PRIMARY KEY ( FACILITY_NO ) ;

CREATE TABLE ATTRACT_AVAILAVLE_LIST 
    ( 
     ATTRACT_RESERVE_TIME DATE , 
     ATTRACT_AVAIL_AMOUNT INTEGER , 
     FACILITY_NO          INTEGER  NOT NULL 
    ) 
;

ALTER TABLE ATTRACT_AVAILAVLE_LIST 
    ADD CONSTRAINT PKv1 PRIMARY KEY ( FACILITY_NO ) ;

CREATE TABLE ATTRACT_RESERVE 
    ( 
     CUSTOMER_NO             INTEGER  NOT NULL , 
     ATTRACT_RESERVE_PERSON INTEGER , 
     ATTRACT_RESERVE_DATE   DATE , 
     FACILITY_NO            INTEGER  NOT NULL 
    ) 
;

ALTER TABLE ATTRACT_RESERVE 
    ADD CONSTRAINT PKv2 PRIMARY KEY ( FACILITY_NO ) ;

CREATE TABLE CUSTOMER 
(
  CUSTOMER_NAME      VARCHAR(20) NOT NULL,
  CUSTOMER_BIRTH_DATE DATE,
  CUSTOMER_MOBILE    VARCHAR(100),
  CUSTOMER_ADDRESS   VARCHAR(100),
  CUSTOMER_NO        INTEGER NOT NULL AUTO_INCREMENT,
  CUSTOMER_ID        VARCHAR(100),
  CUSTOMER_PASSWORD  VARCHAR(100),
  TICKET_NO          INTEGER NOT NULL,
  PRIMARY KEY (CUSTOMER_NO)
);


CREATE TABLE EVENT_SCHEDULE 
    ( 
     EVENT_NO INTEGER NOT NULL AUTO_INCREMENT,
     EVENT_NAME     VARCHAR (100)  NOT NULL , 
     EVENT_SCHEDULE VARCHAR (100) , 
     EVENT_DETAIL   VARCHAR (100) , 
     EVENT_COST     INTEGER , 
     EVENT_LOCATION VARCHAR (100) ,
     PRIMARY KEY (EVENT_NO)
    ) 
;


CREATE TABLE FACILITY 
    ( 
     FACILITY_NO        INTEGER  NOT NULL AUTO_INCREMENT, 
     FACILITY_CODE      VARCHAR (100)  NOT NULL , 
     FACILITY_NAME      VARCHAR (100) , 
     FACILITY_RUN_TIME  VARCHAR (100) , 
     FACILITY_LATITUDE  DECIMAL (16,10) , 
     FACILITY_LONGITUDE DECIMAL (16,10) ,
     PRIMARY KEY (FACILITY_NO)
    ) 
;


CREATE TABLE TICKET 
    ( 
     TICKET_NO           INTEGER  NOT NULL AUTO_INCREMENT, 
     TICKET_NAME         VARCHAR (100) , 
     TICKET_RESERVE_DATE DATE , 
     ADULT               INTEGER , 
     CHILDREN            INTEGER ,
     PRIMARY KEY ( TICKET_NO )
    ) 
;


ALTER TABLE ATTRACT_AVAILAVLE_LIST 
    ADD CONSTRAINT ATTRACT_AVAILAVLE_LIST_FK FOREIGN KEY 
    ( 
     FACILITY_NO
    ) 
    REFERENCES ATTRACT 
    ( 
     FACILITY_NO
    ) 
;

ALTER TABLE ATTRACT_RESERVE 
    ADD CONSTRAINT ATTRACT_RESERVE_FK FOREIGN KEY 
    ( 
     FACILITY_NO
    ) 
    REFERENCES ATTRACT 
    ( 
     FACILITY_NO
    ) 
;

ALTER TABLE ATTRACT_RESERVE 
    ADD CONSTRAINT ATTRACT_RESERVE_FKv2 FOREIGN KEY 
    ( 
     CUSTOMER_NO
    ) 
    REFERENCES CUSTOMER 
    ( 
     CUSTOMER_NO
    ) 
;

ALTER TABLE ATTRACT 
    ADD CONSTRAINT ATTRACT_FK FOREIGN KEY 
    ( 
     FACILITY_NO
    ) 
    REFERENCES FACILITY 
    ( 
     FACILITY_NO
    ) 
;

ALTER TABLE CUSTOMER 
    ADD CONSTRAINT CUSTOMER_FK FOREIGN KEY 
    ( 
     TICKET_NO
    ) 
    REFERENCES TICKET 
    ( 
     TICKET_NO
    ) 
;

